-- ============================================================================
--  AUXION - PostgreSQL schema
-- ============================================================================
--  Port del modelo relacional base (SQLite) a PostgreSQL. Criterio:
--   - Se conservan los nombres de tablas y columnas usados por la app,
--     incluyendo el camelCase. Como Postgres pasa a minuscula los identificadores
--     sin comillas, se citan con comillas dobles para preservar el caso.
--   - Los estados heredados con typos fueron normalizados para que los contratos
--     actuales usen nombres legibles y consistentes.
--   - Traduccion de tipos SQLite -> PostgreSQL:
--        INTEGER PRIMARY KEY AUTOINCREMENT -> integer GENERATED BY DEFAULT AS IDENTITY
--        REAL monetario                    -> numeric(15,2)
--        BLOB                              -> bytea
--        TEXT                              -> text
--        DEFAULT CURRENT_TIMESTAMP (texto) -> DEFAULT to_char(now() at time zone 'utc', ...)
--   - Las FK se aplican siempre (Postgres no necesita el pragma foreign_keys).
--   - This portfolio version targets a local PostgreSQL database for reproducible evaluation.
--
--  Las tablas con prefijo `app_` son auxiliares de la app movil (auth, medios de
--  pago, tiempos de la sala en vivo, mensajeria) y complementan el modelo base.
-- ============================================================================


-- ==========================  MODELO RELACIONAL BASE  ==========================

CREATE TABLE IF NOT EXISTS "paises" (
  "numero" integer NOT NULL,
  "nombre" text NOT NULL,
  "nombreCorto" text,
  "capital" text NOT NULL,
  "nacionalidad" text NOT NULL,
  "idiomas" text NOT NULL,
  CONSTRAINT pk_paises PRIMARY KEY ("numero")
);

CREATE TABLE IF NOT EXISTS "personas" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "documento" text NOT NULL,
  "nombre" text NOT NULL,
  "direccion" text,
  "estado" text CHECK ("estado" IN ('activo','inactivo')),
  "foto" bytea
);

-- NOTA: empleados se mantiene como entidad independiente de personas para
-- conservar compatibilidad con las relaciones existentes del modelo.
CREATE TABLE IF NOT EXISTS "empleados" (
  "identificador" integer NOT NULL,
  "cargo" text,
  "sector" integer,
  CONSTRAINT pk_empleados PRIMARY KEY ("identificador")
);

CREATE TABLE IF NOT EXISTS "sectores" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombreSector" text NOT NULL,
  "codigoSector" text,
  "responsableSector" integer,
  CONSTRAINT fk_sectores_empleados FOREIGN KEY ("responsableSector") REFERENCES "empleados" ("identificador")
);

CREATE TABLE IF NOT EXISTS "seguros" (
  "nroPoliza" text NOT NULL,
  "compania" text NOT NULL,
  "polizaCombinada" text CHECK ("polizaCombinada" IN ('si','no')),
  "importe" numeric(15,2) NOT NULL CHECK ("importe" > 0),
  CONSTRAINT pk_seguro PRIMARY KEY ("nroPoliza")
);

CREATE TABLE IF NOT EXISTS "clientes" (
  "identificador" integer NOT NULL,
  "numeroPais" integer,
  "admitido" text CHECK ("admitido" IN ('si','no')),
  "categoria" text CHECK ("categoria" IN ('comun','especial','plata','oro','platino')),
  "verificador" integer NOT NULL,
  CONSTRAINT pk_clientes PRIMARY KEY ("identificador"),
  CONSTRAINT fk_clientes_personas FOREIGN KEY ("identificador") REFERENCES "personas" ("identificador"),
  CONSTRAINT fk_clientes_empleados FOREIGN KEY ("verificador") REFERENCES "empleados" ("identificador"),
  CONSTRAINT fk_clientes_paises FOREIGN KEY ("numeroPais") REFERENCES "paises" ("numero")
);

CREATE TABLE IF NOT EXISTS "duenios" (
  "identificador" integer NOT NULL,
  "numeroPais" integer,
  "verificacionFinanciera" text CHECK ("verificacionFinanciera" IN ('si','no')),
  "verificacionJudicial" text CHECK ("verificacionJudicial" IN ('si','no')),
  "calificacionRiesgo" integer CHECK ("calificacionRiesgo" IN (1,2,3,4,5,6)),
  "verificador" integer NOT NULL,
  CONSTRAINT pk_duenios PRIMARY KEY ("identificador"),
  CONSTRAINT fk_duenios_personas FOREIGN KEY ("identificador") REFERENCES "personas" ("identificador"),
  CONSTRAINT fk_duenios_empleados FOREIGN KEY ("verificador") REFERENCES "empleados" ("identificador")
);

CREATE TABLE IF NOT EXISTS "subastadores" (
  "identificador" integer NOT NULL,
  "matricula" text,
  "region" text,
  CONSTRAINT pk_subastadores PRIMARY KEY ("identificador"),
  CONSTRAINT fk_subastadores_personas FOREIGN KEY ("identificador") REFERENCES "personas" ("identificador")
);

CREATE TABLE IF NOT EXISTS "subastas" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" text,
  "hora" text NOT NULL,
  "estado" text CHECK ("estado" IN ('abierta','cerrada')),
  "subastador" integer,
  "ubicacion" text,
  "capacidadAsistentes" integer,
  "tieneDeposito" text CHECK ("tieneDeposito" IN ('si','no')),
  "seguridadPropia" text CHECK ("seguridadPropia" IN ('si','no')),
  "categoria" text CHECK ("categoria" IN ('comun','especial','plata','oro','platino')),
  CONSTRAINT fk_subastas_subastadores FOREIGN KEY ("subastador") REFERENCES "subastadores" ("identificador")
);

CREATE TABLE IF NOT EXISTS "productos" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" text,
  "disponible" text CHECK ("disponible" IN ('si','no')),
  "descripcionCatalogo" text DEFAULT 'No Posee',
  "descripcionCompleta" text NOT NULL,
  "revisor" integer NOT NULL,
  "duenio" integer NOT NULL,
  "seguro" text,
  CONSTRAINT fk_productos_empleados FOREIGN KEY ("revisor") REFERENCES "empleados" ("identificador"),
  CONSTRAINT fk_productos_duenios FOREIGN KEY ("duenio") REFERENCES "duenios" ("identificador")
);

CREATE TABLE IF NOT EXISTS "fotos" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "producto" integer NOT NULL,
  "foto" bytea NOT NULL,
  CONSTRAINT fk_fotos_productos FOREIGN KEY ("producto") REFERENCES "productos" ("identificador")
);

CREATE TABLE IF NOT EXISTS "catalogos" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descripcion" text NOT NULL,
  "subasta" integer,
  "responsable" integer NOT NULL,
  CONSTRAINT fk_catalogos_empleados FOREIGN KEY ("responsable") REFERENCES "empleados" ("identificador"),
  CONSTRAINT fk_catalogos_subastas FOREIGN KEY ("subasta") REFERENCES "subastas" ("identificador")
);

CREATE TABLE IF NOT EXISTS "itemsCatalogo" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "catalogo" integer NOT NULL,
  "producto" integer NOT NULL,
  "precioBase" numeric(15,2) NOT NULL CHECK ("precioBase" > 0.01),
  "comision" numeric(15,2) NOT NULL CHECK ("comision" > 0.01),
  "subastado" text CHECK ("subastado" IN ('si','no')),
  CONSTRAINT fk_itemsCatalogo_catalogos FOREIGN KEY ("catalogo") REFERENCES "catalogos" ("identificador"),
  CONSTRAINT fk_itemsCatalogo_productos FOREIGN KEY ("producto") REFERENCES "productos" ("identificador")
);

CREATE TABLE IF NOT EXISTS "asistentes" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "numeroPostor" integer NOT NULL,
  "cliente" integer NOT NULL,
  "subasta" integer NOT NULL,
  CONSTRAINT fk_asistentes_clientes FOREIGN KEY ("cliente") REFERENCES "clientes" ("identificador"),
  CONSTRAINT fk_asistentes_subasta FOREIGN KEY ("subasta") REFERENCES "subastas" ("identificador")
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_asistentes_cliente_subasta ON "asistentes" ("cliente","subasta");

CREATE TABLE IF NOT EXISTS "pujos" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asistente" integer NOT NULL,
  "item" integer NOT NULL,
  "importe" numeric(15,2) NOT NULL CHECK ("importe" > 0.01),
  "ganador" text CHECK ("ganador" IN ('si','no')) DEFAULT 'no',
  CONSTRAINT fk_pujos_asistentes FOREIGN KEY ("asistente") REFERENCES "asistentes" ("identificador"),
  CONSTRAINT fk_pujos_itemsCatalogo FOREIGN KEY ("item") REFERENCES "itemsCatalogo" ("identificador")
);
CREATE INDEX IF NOT EXISTS idx_pujos_item_importe ON "pujos" ("item","importe" DESC,"identificador" DESC);

CREATE TABLE IF NOT EXISTS "registroDeSubasta" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subasta" integer NOT NULL,
  "duenio" integer NOT NULL,
  "producto" integer NOT NULL,
  "cliente" integer NOT NULL,
  "importe" numeric(15,2) NOT NULL CHECK ("importe" > 0.01),
  "comision" numeric(15,2) NOT NULL CHECK ("comision" > 0.01),
  CONSTRAINT fk_registroDeSubasta_subastas FOREIGN KEY ("subasta") REFERENCES "subastas" ("identificador"),
  CONSTRAINT fk_registroDeSubasta_duenios FOREIGN KEY ("duenio") REFERENCES "duenios" ("identificador"),
  CONSTRAINT fk_registroDeSubasta_producto FOREIGN KEY ("producto") REFERENCES "productos" ("identificador"),
  CONSTRAINT fk_registroDeSubasta_cliente FOREIGN KEY ("cliente") REFERENCES "clientes" ("identificador")
);


-- ===================  TABLAS AUXILIARES DE LA APLICACION  ====================

CREATE TABLE IF NOT EXISTS "app_credenciales" (
  "persona" integer NOT NULL,
  "email" text NOT NULL UNIQUE,
  "passwordHash" text NOT NULL,
  "cuentaCobroBanco" text,
  "cuentaCobroCbu" text,
  "cuentaCobroAlias" text,
  CONSTRAINT pk_app_credenciales PRIMARY KEY ("persona"),
  CONSTRAINT fk_app_credenciales_personas FOREIGN KEY ("persona") REFERENCES "personas" ("identificador")
);

CREATE TABLE IF NOT EXISTS "app_pre_registros" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona" integer NOT NULL,
  "cliente" integer NOT NULL,
  "email" text NOT NULL UNIQUE,
  "imagenDniFrente" text NOT NULL,
  "imagenDniDorso" text NOT NULL,
  "estado" text NOT NULL DEFAULT 'pendiente' CHECK ("estado" IN ('pendiente','aprobado','rechazado','completado')),
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  "actualizadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  "verificacionDisponibleEn" text NOT NULL,
  "categoriaAsignada" text CHECK ("categoriaAsignada" IN ('comun','especial','plata','oro','platino')),
  "tokenRegistro" text UNIQUE,
  "tokenExpiraEn" text,
  "aprobadoEn" text,
  "completadoEn" text,
  CONSTRAINT fk_app_pre_registros_personas FOREIGN KEY ("persona") REFERENCES "personas" ("identificador"),
  CONSTRAINT fk_app_pre_registros_clientes FOREIGN KEY ("cliente") REFERENCES "clientes" ("identificador")
);
CREATE INDEX IF NOT EXISTS idx_app_pre_registros_estado_fecha ON "app_pre_registros" ("estado","verificacionDisponibleEn");

CREATE TABLE IF NOT EXISTS "app_password_resets" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona" integer NOT NULL,
  "email" text NOT NULL,
  "token" text NOT NULL UNIQUE,
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  "expiraEn" text NOT NULL,
  "usadoEn" text,
  CONSTRAINT fk_app_password_resets_credenciales FOREIGN KEY ("persona") REFERENCES "app_credenciales" ("persona")
);
CREATE INDEX IF NOT EXISTS idx_app_password_resets_email ON "app_password_resets" ("email","usadoEn","expiraEn");

CREATE TABLE IF NOT EXISTS "app_mediosPago" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente" integer NOT NULL,
  "tipo" text NOT NULL CHECK ("tipo" IN ('tarjeta','cuenta_bancaria','cheque_certificado')),
  "alias" text NOT NULL,
  "moneda" text NOT NULL CHECK ("moneda" IN ('ARS','USD')),
  "numero" text,
  "banco" text,
  "montoGarantia" numeric(15,2),
  "verificado" integer NOT NULL DEFAULT 0,
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT fk_app_mediosPago_clientes FOREIGN KEY ("cliente") REFERENCES "clientes" ("identificador")
);
CREATE INDEX IF NOT EXISTS idx_app_mediosPago_cliente_verificado ON "app_mediosPago" ("cliente","verificado");

CREATE TABLE IF NOT EXISTS "app_pujaMedioPago" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pujo" integer NOT NULL,
  "medioPago" integer NOT NULL,
  "cliente" integer NOT NULL,
  "moneda" text NOT NULL CHECK ("moneda" IN ('ARS','USD')),
  "monto" numeric(15,2) NOT NULL CHECK ("monto" > 0),
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT uq_app_pujaMedioPago_pujo UNIQUE ("pujo"),
  CONSTRAINT fk_app_pujaMedioPago_pujos FOREIGN KEY ("pujo") REFERENCES "pujos" ("identificador"),
  CONSTRAINT fk_app_pujaMedioPago_mediosPago FOREIGN KEY ("medioPago") REFERENCES "app_mediosPago" ("identificador"),
  CONSTRAINT fk_app_pujaMedioPago_clientes FOREIGN KEY ("cliente") REFERENCES "clientes" ("identificador")
);

CREATE TABLE IF NOT EXISTS "app_subastaRuntime" (
  "subasta" integer NOT NULL,
  "moneda" text NOT NULL DEFAULT 'ARS' CHECK ("moneda" IN ('ARS','USD')),
  "abiertaEn" text,
  "inicioProgramado" text,
  CONSTRAINT pk_app_subastaRuntime PRIMARY KEY ("subasta"),
  CONSTRAINT fk_app_subastaRuntime_subastas FOREIGN KEY ("subasta") REFERENCES "subastas" ("identificador")
);

CREATE TABLE IF NOT EXISTS "app_mensajes" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona" integer NOT NULL,
  "titulo" text NOT NULL,
  "cuerpo" text NOT NULL,
  "tipo" text NOT NULL CHECK ("tipo" IN ('mensaje','alerta')),
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT fk_app_mensajes_personas FOREIGN KEY ("persona") REFERENCES "personas" ("identificador")
);

CREATE TABLE IF NOT EXISTS "app_articulos" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "persona" integer NOT NULL,
  "titulo" text NOT NULL,
  "descripcion" text NOT NULL,
  "imagenFrente" text,
  "imagenDorso" text,
  "precioEstimado" numeric(15,2),
  "estado" text NOT NULL DEFAULT 'propuesta' CHECK ("estado" IN ('propuesta','en_revision','aprobado','rechazado','en_subasta','vendido')),
  "condicionesVenta" text,
  "producto" integer,
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT fk_app_articulos_personas FOREIGN KEY ("persona") REFERENCES "personas" ("identificador"),
  CONSTRAINT fk_app_articulos_productos FOREIGN KEY ("producto") REFERENCES "productos" ("identificador")
);

CREATE TABLE IF NOT EXISTS "app_articuloDocumentacion" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "articulo" integer NOT NULL,
  "fotos" text NOT NULL DEFAULT '[]',
  "informacionHistorica" text,
  "documentoOrigen" text,
  "declaracionPropiedad" text NOT NULL,
  "aceptaDevolucionConCargo" integer NOT NULL DEFAULT 0 CHECK ("aceptaDevolucionConCargo" IN (0,1)),
  "aceptaCondiciones" integer CHECK ("aceptaCondiciones" IN (0,1)),
  "condicionesRespondidasEn" text,
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  "actualizadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT uq_app_articuloDocumentacion_articulo UNIQUE ("articulo"),
  CONSTRAINT fk_app_articuloDocumentacion_articulos FOREIGN KEY ("articulo") REFERENCES "app_articulos" ("identificador")
);

CREATE TABLE IF NOT EXISTS "app_articuloSeguimiento" (
  "identificador" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "articulo" integer NOT NULL,
  "estado" text NOT NULL,
  "descripcion" text NOT NULL,
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT fk_app_articuloSeguimiento_articulos FOREIGN KEY ("articulo") REFERENCES "app_articulos" ("identificador")
);

-- Optional image URL for each product/lot. The original `productos` table does
-- not model image URLs, so the app keeps this small auxiliary table.
CREATE TABLE IF NOT EXISTS "app_productoImagen" (
  "producto" integer NOT NULL,
  "url" text NOT NULL,
  "creadoEn" text NOT NULL DEFAULT to_char(now() at time zone 'utc','YYYY-MM-DD HH24:MI:SS'),
  CONSTRAINT pk_app_productoImagen PRIMARY KEY ("producto"),
  CONSTRAINT fk_app_productoImagen_productos FOREIGN KEY ("producto") REFERENCES "productos" ("identificador")
);

-- =========================  IDEMPOTENT NORMALIZATION  =========================

ALTER TABLE "personas" DROP CONSTRAINT IF EXISTS personas_estado_check;
UPDATE "personas" SET "estado" = 'inactivo' WHERE "estado" = 'incativo';
ALTER TABLE "personas"
  ADD CONSTRAINT personas_estado_check CHECK ("estado" IN ('activo','inactivo'));

ALTER TABLE "subastas" DROP CONSTRAINT IF EXISTS subastas_estado_check;
UPDATE "subastas" SET "estado" = 'cerrada' WHERE "estado" = 'carrada';
ALTER TABLE "subastas"
  ADD CONSTRAINT subastas_estado_check CHECK ("estado" IN ('abierta','cerrada'));

ALTER TABLE "seguros"
  ALTER COLUMN "importe" TYPE numeric(15,2) USING "importe"::numeric(15,2);
ALTER TABLE "itemsCatalogo"
  ALTER COLUMN "precioBase" TYPE numeric(15,2) USING "precioBase"::numeric(15,2),
  ALTER COLUMN "comision" TYPE numeric(15,2) USING "comision"::numeric(15,2);
ALTER TABLE "pujos"
  ALTER COLUMN "importe" TYPE numeric(15,2) USING "importe"::numeric(15,2);
ALTER TABLE "registroDeSubasta"
  ALTER COLUMN "importe" TYPE numeric(15,2) USING "importe"::numeric(15,2),
  ALTER COLUMN "comision" TYPE numeric(15,2) USING "comision"::numeric(15,2);
ALTER TABLE "app_mediosPago"
  ALTER COLUMN "montoGarantia" TYPE numeric(15,2) USING "montoGarantia"::numeric(15,2);
ALTER TABLE "app_pujaMedioPago"
  ALTER COLUMN "monto" TYPE numeric(15,2) USING "monto"::numeric(15,2);
ALTER TABLE "app_articulos"
  ALTER COLUMN "precioEstimado" TYPE numeric(15,2) USING "precioEstimado"::numeric(15,2);
